// import { Metadata } from "next"

// export const metadata: Metadata = {
//   title: {
//     // absolute: '',
//     default: 'Next.js Tutorial',
//     template: '%s | VargasDev',
//   },
//   description: 'Generated by Next.js',
// }
import { Metadata } from "next"

export const metadata: Metadata ={
  title: {
    // absolute: ''
    default: 'Next.js Tutorial',
    template: '%s | VargasDev',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <header style={{backgroundColor: 'lightblue', padding:'1rem'}}>Header</header>
        {children}
        <footer style={{backgroundColor: 'ghostwhite', padding: '1rem'}}>Footer</footer>
        </body>
    </html>
  )
}
